export class ServerConfig {

    ServerId;
    GMA_RoleOnJoin;
    GMA_RoleToAssignOnJoin;
    GMA_AddWelcomeMessage;
    GMA_AddWelcomeMessageChannel;
    GMA_AddWelcomeMessageChannelBackup;
    GMA_AddWelcomeMessageEmojiReaction;
    GMR_LogMemberLeave;
    GMR_LogMemberLeaveChannel;
    GMR_LogMemberLeaveChannelBackup;
    GMU_LogNicknameChanges;
    GMU_LogNicknameChangesChannel;
    M_UseRegexSPAMProtection;
    M_RegexSPAMProtectionChannel;
    M_AssignRoleOnMessage;
    M_RoleToAssignOnMessage;
    M_MessageRegexWhoIs;
    M_SBGFaq;
    M_SBGFaqValidChannels;
    M_SendSpamAfterMessages;
    M_QuantityOfMessagesAfterSpam;
    MD_SaveMessageDeletionLogs;
    MD_MessageDeletionLogsChannel;
    MRA_UseMessageReaction;
    MRA_MessageIdToReact;
    MRA_RoleToToggleOnReact;
    MRA_RemoveReactionsOnModerationThreads;
    MU_LogMessageUpdates;
    MU_ChannelToLogMessageUpdates;
    NP_EnableNowPlayingRoles;
    NP_LookingToPlayRole;
    NP_NowPlayingRole;
    NP_ActivityName;
    PC_EnablePolling;
    PC_UrlToPoll;
    PC_PropertyTreeId;
    PC_ChannelToPostAlert;
    PC_LastFetchedId;

    constructor() {
        this.ServerId                               = "";
        this.GMA_RoleOnJoin                         = false;
        this.GMA_RoleToAssignOnJoin                 = "";
        this.GMA_AddWelcomeMessage                  = false;
        this.GMA_AddWelcomeMessageChannel           = "";
        this.GMA_AddWelcomeMessageChannelBackup     = "";
        this.GMA_AddWelcomeMessageEmojiReaction     = "";
        this.GMR_LogMemberLeave                     = false;
        this.GMR_LogMemberLeaveChannel              = "";
        this.GMR_LogMemberLeaveChannelBackup        = "";
        this.GMU_LogNicknameChanges                 = false;
        this.GMU_LogNicknameChangesChannel          = "";
        this.M_UseRegexSPAMProtection               = false;
        this.M_RegexSPAMProtectionChannel           = "";
        this.M_AssignRoleOnMessage                  = false;
        this.M_RoleToAssignOnMessage                = "";
        this.M_MessageRegexWhoIs                    = false;
        this.M_SBGFaq                               = false;
        this.M_SBGFaqValidChannels                  = "";
        this.M_SendSpamAfterMessages                = false;
        this.M_QuantityOfMessagesAfterSpam          = 2000;
        this.MD_SaveMessageDeletionLogs             = false;
        this.MD_MessageDeletionLogsChannel          = "";
        this.MRA_UseMessageReaction                 = false;
        this.MRA_MessageIdToReact                   = "";
        this.MRA_RoleToToggleOnReact                = "";
        this.MRA_RemoveReactionsOnModerationThreads = false;
        this.MU_LogMessageUpdates                   = false;
        this.MU_ChannelToLogMessageUpdates          = "";
        this.NP_EnableNowPlayingRoles               = false;
        this.NP_LookingToPlayRole                   = "";
        this.NP_NowPlayingRole                      = "";
        this.NP_ActivityName                        = "";
        this.PC_EnablePolling                       = false;
        this.PC_UrlToPoll                           = "";
        this.PC_PropertyTreeId                      = "";
        this.PC_ChannelToPostAlert                  = "";
        this.PC_LastFetchedId                       = "";
    }
}